import type { Category, CategoryPayload } from '@/features/categories/types'
import { http, serialiseListQuery } from '@/shared/api'
import { withSignal, type Resource } from '@/shared/api/types'
import type { ListResponse } from '@/shared/types/api'
import type { BulkRequest, BulkResult } from '@/shared/types/bulk'

const BASE = '/categories'

/**
 * Category endpoints.
 *
 * Implements the shared `Resource` contract so cross-cutting behaviour can be written once
 * against every entity, while the URLs stay spelled out here rather than generated by a
 * factory — the endpoint being called is visible at the place it is called.
 */
export const categoriesApi: Resource<Category, CategoryPayload> & {
  bulk(payload: BulkRequest, signal?: AbortSignal): Promise<BulkResult>
} = {
  /**
   * Applies one action to many records.
   *
   * A single request, not N: the server reports per record, so the client learns which
   * succeeded and why the rest did not — information a loop of individual calls would have to
   * reassemble, and would lose the moment one of them threw.
   */
  bulk: (payload: BulkRequest, signal?: AbortSignal) =>
    http.post<BulkResult>(`${BASE}/bulk`, payload, withSignal(signal)),
  list: (query, signal) =>
    http.get<ListResponse<Category>>(BASE, {
      ...withSignal(signal),
      query: serialiseListQuery(query),
    }),

  get: (id, signal) => http.get<Category>(`${BASE}/${encodeURIComponent(id)}`, withSignal(signal)),

  create: (payload, signal) => http.post<Category>(BASE, payload, withSignal(signal)),

  update: (id, payload, signal) =>
    http.patch<Category>(`${BASE}/${encodeURIComponent(id)}`, payload, withSignal(signal)),

  remove: (id, signal) =>
    http.delete<void>(`${BASE}/${encodeURIComponent(id)}`, withSignal(signal)),
}
